# Generated by Django 2.2.17 on 2021-01-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.CharField(blank=True, max_length=255, null=True)),
                ('class_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_num', models.IntegerField()),
            ],
        ),
    ]
